# training
epochs: 1000
lr: 0.002
weight_decay: 0
drop_prob: 0.7

# network
accum: max
hidden_size: 
  - 500
  - 75
num_basis: 2
rgc_bn: False
rgc_relu: True
dense_bn: False
dense_relu: True
bidec_drop: False

# dataset
root: data/ml-10m
dataset_name: ml-10M100K
#root: data/ml-100k
#dataset_name: ml-100k

# comet-ml (optional)
workspace: 
project_name: 
api_key: 

# environment
gpu_id: 0 # -1 mean cpu
